### ISSUE TITLE
[BUG] Problem when using anki on arch linux

### ISSUE THREAD

**Issue by Tresillo2017** [Foxy-null/AnkiCraft#18]
## Describe the bug
The add-on won't load

## Debug Information
```less
Anki 24.11 (8e5efc59) (src) (ao)
Python 3.13.1 Qt 6.8.1 PyQt 6.8.0
Platform: Linux-6.12.7-arch1-1-x86_64-with-glibc2.40

When loading AnkiCraft:
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/aqt/addons.py", line 250, in loadAddons
    __import__(addon.dir_name)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/home/tomas/.local/share/Anki2/addons21/368161874/__init__.py", line 16, in <module>
    from . import main
  File "/home/tomas/.local/share/Anki2/addons21/368161874/main.py", line 36, in <module>
    from .controllers import (
    ...<3 lines>...
    )
  File "/home/tomas/.local/share/Anki2/addons21/368161874/controllers.py", line 14, in <module>
    from . import leaderboards
  File "/home/tomas/.local/share/Anki2/addons21/368161874/leaderboards.py", line 12, in <module>
    from .persistence import PersistedAchievement, min_datetime
  File "/home/tomas/.local/share/Anki2/addons21/368161874/persistence.py", line 6, in <module>
    from ._vendor.yoyo import get_backend
  File "/home/tomas/.local/share/Anki2/addons21/368161874/_vendor/yoyo/__init__.py", line 27, in <module>
    from .connections import get_backend
  File "/home/tomas/.local/share/Anki2/addons21/368161874/_vendor/yoyo/connections.py", line 23, in <module>
    from .migrations import default_migration_table
  File "/home/tomas/.local/share/Anki2/addons21/368161874/_vendor/yoyo/migrations.py", line 44, in <module>
    from .utils import plural
  File "/home/tomas/.local/share/Anki2/addons21/368161874/_vendor/yoyo/utils.py", line 23, in <module>
    from .config import CONFIG_EDITOR_KEY
  File "/home/tomas/.local/share/Anki2/addons21/368161874/_vendor/yoyo/config.py", line 19, in <module>
    from .. import iniherit
  File "/home/tomas/.local/share/Anki2/addons21/368161874/_vendor/iniherit/__init__.py", line 9, in <module>
    from .parser import *
  File "/home/tomas/.local/share/Anki2/addons21/368161874/_vendor/iniherit/parser.py", line 37, in <module>
    _real_SafeConfigParser = CP.SafeConfigParser
                             ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
```

## To Reproduce
1. Open Anki
2. See error

## Screenshots (optional)
![image](https://github.com/user-attachments/assets/462b9623-47b6-450e-be9c-0d79258b695c)

## Environment
 - OS: Arch Linux
 - Anki Version: 24.11

**Comment by Foxy-null** [comment]
Thank you for reaching out. I tested AnkiCraft on my Debian Linux system, and it is functioning properly. I'm not very familiar with Arch Linux, but I will try running it in my virtual environment.

**Comment by Foxy-null** [comment]
I also tested it on Linux version 5.15.167.4-arch, and it functioned correctly. Have you considered disabling all other addons?
![msrdc_20241231_133333_1135](https://github.com/user-attachments/assets/5ba1b4cd-e500-4059-843d-a79a53c6d2c7)

**Comment by Tresillo2017** [comment]
Disabled all add-ons but still happens

**Comment by Foxy-null** [comment]
I discovered that the error is due to the Python version used by your Anki installation. Please try changing the Python version to 3.9.x, as recommended in the official Anki documentation.

https://github.com/ankitects/anki/blob/main/docs/development.md

**Comment by Foxy-null** [comment]
I recently began using Arch Linux, so I inquired with Perplexity about how to change the Python version used by Anki. Just for your information, here’s the link:

https://www.perplexity.ai/search/how-to-specify-the-python-vers-klwOQeVOTYmsbaV4W2vuMg
