### ISSUE TITLE
Some nether items are not showing properly

### ISSUE THREAD

**Issue by Foxy-null** [Foxy-null/AnkiCraft#3]
タイトル訳：ネザーのアイテムが正しく表示されない

AnkiWebで報告されたものを転載しました。
(This issue is came from AnkiWeb.)
![image](https://github.com/Foxy-null/AnkiCraft/assets/72304646/c2029a5c-b7c8-4f74-ad89-e36c541b5e90)

以下はコメントして頂いたデバック情報です。
(The following debug info is what I got from the comment.)

```Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: Linux-5.15.0-79-generic-x86_64-with-glibc2.31
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-08-30 04:29:39
Add-ons possibly involved: ⁨AnkiCraft, Deck name in title 21⁩

Traceback (most recent call last):
  File "aqt.main", line 609, in loadCollection
  File "aqt.main", line 712, in moveToState
  File "aqt.main", line 718, in _deckBrowserState
  File "/home/User/.local/share/Anki2/addons21/699175524/__init__.py", line 44, in wrapped
    orig(*args, **kwargs)
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 80, in repl
  File "aqt.deckbrowser", line 73, in show
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 81, in repl
  File "/home/User/.local/share/Anki2/addons21/368161874/main.py", line 223, in inject_medals_with_js
    view(
  File "/home/User/.local/share/Anki2/addons21/368161874/views.py", line 29, in TodaysMedalsJS
    html=MedalsOverview(
  File "/home/User/.local/share/Anki2/addons21/368161874/views.py", line 115, in MedalsOverview
    return template.render(
  File "/home/User/.local/share/Anki2/addons21/368161874/_vendor/jinja2/environment.py", line 1094, in render
    self.environment.handle_exception()
  File "/home/User/.local/share/Anki2/addons21/368161874/_vendor/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/User/.local/share/Anki2/addons21/368161874/_vendor/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 47, in top-level template code
  File "/home/User/.local/share/Anki2/addons21/368161874/_vendor/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "/home/User/.local/share/Anki2/addons21/368161874/views.py", line 94, in img_base64
    with open(self.img_src, "rb") as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/User/.local/share/Anki2/addons21/368161874/images/halo_infinite/Warped_Stem.png'
Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 274, in on_focus_changed
  File "_aqt.hooks", line 3236, in __call__
  File "aqt.main", line 806, in on_focus_did_change
  File "aqt.deckbrowser", line 81, in refresh_if_needed
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 81, in repl
  File "/home/User/.local/share/Anki2/addons21/368161874/main.py", line 223, in inject_medals_with_js
    view(
  File "/home/User/.local/share/Anki2/addons21/368161874/views.py", line 29, in TodaysMedalsJS
    html=MedalsOverview(
  File "/home/User/.local/share/Anki2/addons21/368161874/views.py", line 115, in MedalsOverview
    return template.render(
  File "/home/User/.local/share/Anki2/addons21/368161874/_vendor/jinja2/environment.py", line 1094, in render
    self.environment.handle_exception()
  File "/home/User/.local/share/Anki2/addons21/368161874/_vendor/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/User/.local/share/Anki2/addons21/368161874/_vendor/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 47, in top-level template code
  File "/home/User/.local/share/Anki2/addons21/368161874/_vendor/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "/home/User/.local/share/Anki2/addons21/368161874/views.py", line 94, in img_base64
    with open(self.img_src, "rb") as image_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/User/.local/share/Anki2/addons21/368161874/images/halo_infinite/Warped_Stem.png'```

**Comment by Foxy-null** [comment]
AnkiWebに間違えて古いバージョンをアップロードしていたのが原因みたいです。ごめん！
(Seems like it was because I uploaded outdated version to AnkiWeb. Sorry!!)
