### ISSUE TITLE
New error after update?

### ISSUE THREAD

**Issue by ShawnO33** [Foxy-null/AnkiCraft#4]
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨AnkiCraft⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "/Users/user1/Library/Application Support/Anki2/addons21/368161874/__init__.py", line 16, in <module>
    from . import main
  File "/Users/user1/Library/Application Support/Anki2/addons21/368161874/main.py", line 34, in <module>
    from .controllers import (
  File "/Users/user1/Library/Application Support/Anki2/addons21/368161874/controllers.py", line 13, in <module>
    from . import leaderboards
  File "/Users/user1/Library/Application Support/Anki2/addons21/368161874/leaderboards.py", line 12, in <module>
    from .persistence import PersistedAchievement, min_datetime
  File "/Users/user1/Library/Application Support/Anki2/addons21/368161874/persistence.py", line 6, in <module>
    from ._vendor.yoyo import get_backend
  File "/Users/user1/Library/Application Support/Anki2/addons21/368161874/_vendor/yoyo/__init__.py", line 27, in <module>
    from .connections import get_backend
  File "/Users/user1/Library/Application Support/Anki2/addons21/368161874/_vendor/yoyo/connections.py", line 23, in <module>
    from .migrations import default_migration_table
  File "/Users/user1/Library/Application Support/Anki2/addons21/368161874/_vendor/yoyo/migrations.py", line 44, in <module>
    from .utils import plural
  File "/Users/user1/Library/Application Support/Anki2/addons21/368161874/_vendor/yoyo/utils.py", line 23, in <module>
    from .config import CONFIG_EDITOR_KEY
  File "/Users/user1/Library/Application Support/Anki2/addons21/368161874/_vendor/yoyo/config.py", line 19, in <module>
    from .. import iniherit
ImportError: cannot import name 'iniherit' from '368161874._vendor' (/Users/user1/Library/Application Support/Anki2/addons21/368161874/_vendor/__init__.py)
⁩

**Comment by Foxy-null** [comment]
I was trying to fix another error and this is what happened, sorry. I'm sorry. Just hold on a little longer.
Thank you for still using addon!

**Comment by ShawnO33** [comment]
No worries, I understand these issues take time. Thanks again.

**Comment by Foxy-null** [comment]
~~Thank you for your understanding! I have updated [v.1.1.1](https://github.com/Foxy-null/AnkiCraft/releases/tag/v1.1.1) and would be happy to know if the update cured the error.~~
Forget it, this fix just caused a new issue.

**Comment by Foxy-null** [comment]
Fixed in [v1.1.2](https://github.com/Foxy-null/AnkiCraft/releases/tag/v1.1.2) update!
Thank you for your continued support!

**Comment by ShawnO33** [comment]
Sorry I forgot to update but yes it works !

**Comment by Foxy-null** [comment]
That's great! Thanks for helping out!
